streams.part1.exercise.Exercise2(Erofeevskiy)
elefus/epam-lab-java8-03-2018 pull request #145
Opened 2018-03-28 10:04 UTC by erofeevskiy-ia

2018-03-31 12:34 UTC, nikita715 approved these changes

2018-03-31 16:09 UTC, jemika requested changes

2018-03-31 16:09 UTC, jemika commented on src/test/java/streams/part1/exercise/Exercise2.java
> +                                   .flatMapToDouble(jh -> DoubleStream.of(jh.get(0)
вроде по заданию нужно брать последнюю позицию в списке

2018-04-02 12:33 UTC, erofeevskiy-ia commented on src/test/java/streams/part1/exercise/Exercise2.java
> +                                   .flatMapToDouble(jh -> DoubleStream.of(jh.get(0)
Да, логично. Странно, что тест проходит. 
@jemika, поправил.

2018-04-02 14:46 UTC, jemika approved these changes

2018-04-26 11:50 UTC, Winner28 approved these changes

2026-08-19 13:41 UTC, closed without merging